name: Lint the list with awesome-lint

on:
  push:
    # Run against master branch only.
    branches: [master]
  pull_request:
    # Include events emitted on code change only.
    types: [opened, synchronize]

jobs:
  awesome-lint-workflow:
    runs-on: ubuntu-latest
    name: Linting with awesome-lint
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install
    # Can only run the tests without fail once the repo is more than 30 days old.
    # - run: npx awesome-lint
